import { vistaraDarkTheme, vistaraTheme, colors, marketingTokens } from "@/theme";

export const designSystem = {
  palette: {
    white: colors.neutral[0],
    surface: colors.neutral[100],
    primary: colors.brand[500],
    primaryDark: colors.brand[600],
    accentBlue: colors.brand[500],
    accentGreen: colors.success[500],
    accentOrange: colors.warning[500],
    accentYellow: colors.warning[500],
    accentRed: colors.error[500],
    accentPurple: colors.indigo[500],
    secondary: colors.brand[500],
    success: colors.success[500],
    warning: colors.warning[500],
    error: colors.error[500],
    info: colors.info[500],
    track: colors.brand[50],
    border: colors.neutral[300],
    borderSoft: colors.neutral[200],
    text: colors.neutral[900],
    textSecondary: colors.neutral[600],
    textTertiary: colors.neutral[500],
    textQuaternary: colors.neutral[400],
    tintSuccess: colors.success[50],
    tintWarning: colors.warning[50],
    tintError: colors.error[50],
    tintPrimary: colors.brand[50],
    tintPurple: colors.brand[50],
  },
  typography: {
    family:
      'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    display: { size: 36, lineHeight: 44, weight: 700 },
    heading: { size: 30, lineHeight: 40, weight: 600 },
    title: { size: 20, lineHeight: 28, weight: 600 },
    bodyLarge: { size: 18, lineHeight: 28, weight: 400 },
    body: { size: 16, lineHeight: 24, weight: 400 },
    caption: { size: 12, lineHeight: 20, weight: 400 },
  },
  spacing: {
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    8: 32,
    10: 40,
    12: 48,
    16: 64,
  },
  radius: {
    sm: 4,
    md: 6,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  elevation: {
    card: "0 2px 4px rgba(7, 17, 31, 0.04), 0 8px 24px rgba(7, 17, 31, 0.08)",
    header: "0 1px 2px rgba(7, 17, 31, 0.04)",
  },
  breakpoints: {
    xs: 480,
    sm: 576,
    md: 768,
    lg: 992,
    xl: 1200,
    xxl: 1600,
  },
  layout: {
    sidebarWidth: 260,
    headerHeight: 72,
    contentPadding: 24,
    sectionGap: 24,
    cardPadding: 24,
    progressHeight: 10,
    marketingMaxWidth: marketingTokens.section.maxWidth,
    marketingGutter: 48,
    marketingGutterTablet: 24,
    marketingGutterMobile: 16,
    marketingSectionY: marketingTokens.section.desktopPadding,
    marketingSectionYMobile: marketingTokens.section.mobilePadding,
  },
} as const;

export const antdTheme = vistaraTheme;
export const darkAntdTheme = vistaraDarkTheme;
